# Generated by Django 4.1 on 2022-08-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('initial_description', models.TextField()),
                ('project_description', models.TextField()),
                ('summary_description', models.TextField()),
                ('image1', models.ImageField(default=None, upload_to='project_images')),
                ('image2', models.ImageField(default=None, upload_to='project_images')),
                ('image3', models.ImageField(default=None, upload_to='project_images')),
                ('github_link', models.URLField(max_length=255)),
                ('live_demo_link', models.URLField(max_length=255)),
            ],
            options={
                'ordering': ['title'],
                'get_latest_by': 'title',
            },
        ),
    ]
