# Generated by Django 4.1 on 2022-09-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('initial_description', models.TextField()),
                ('project_description', models.TextField()),
                ('summary_description', models.TextField()),
                ('main_image', models.ImageField(default=None, upload_to='project_images')),
                ('github_link', models.URLField(max_length=255)),
                ('live_demo_link', models.URLField(max_length=255)),
            ],
            options={
                'ordering': ['title'],
                'get_latest_by': 'title',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='project_images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.project')),
            ],
        ),
    ]
